      <!-- Example row of columns -->
      <div class="row">
      
        <div class="span6">
          <h2></h2>
          <p>Novo modo de gerenciamento de contéudo</p>
       </div>
        <div class="span6">
          
          <h3>Login</h3>
          
          
           <?php 
           
           if($this->msg['tipo'] == "error"){
           		echo '<div class="alert alert-error">';
				switch ($this->msg['cod_msg']) {
					case '1':
						echo "Usuário ou senha inválidos";
						break;
					
					default:
						
						break;
				}
				echo '</div>';
			
           }
           
           ?>
           
		  
		  <?php            
			 $form = $this->form;
			 //$form->setAttribute('action', $this->url('home/action', array('action' => 'faleconosco')));
			 $form->setAttribute('class', 'form-horizontal');
			 $form->prepare();
			 echo $this->form()->openTag($form) . PHP_EOL;
			?>
            <div class="control-group">
			    <label class="control-label" for="inputEmail">Email</label>
			    <div class="controls">
			      <?php echo $this->formInput($form->get('email')); ?>
			      <?php echo $this->formElementErrors($form->get('email')); ?>
			    </div>
			  </div>
			  <div class="control-group">
			    <label class="control-label" for="inputPassword">Password</label>
			    <div class="controls">
			      <?php echo $this->formInput($form->get('senha')); ?>
			      <?php echo $this->formElementErrors($form->get('senha')); ?>
			    </div>
			    
			  </div>
			  <div class="control-group">
			    <div class="controls">
			      <label class="checkbox">
			        <input type="checkbox"> Remember me
			      </label>
			      <button type="submit" class="btn">Sign in</button>
			    </div>
			  </div>
			</form>
          
        </div>
      </div>